### ISSUE TITLE
`open` does not exist in Linux

### ISSUE THREAD

**Issue by illegalprime** [DAHeath/Logic#1]
The uses of `open` here:
https://github.com/DAHeath/Logic/blob/master/src/Data/Graph/Inductive/Extras.hs#L140
and here:
https://github.com/DAHeath/Logic/blob/master/src/Data/Ord/Graph/Extras.hs#L21

should be changed to `xdg-open` on Linux.

**Comment by DAHeath** [comment]
Not sure on the best way to handle this. I guess ideally `open` vs `xdg-open` would be called correctly depending on your OS. I'm not sure how much it really matters though -- this function is almost purely for debugging purposes, so coming up with a complex solution to get it right seems over the top
